apiVersion: apps/v1
kind: Deployment
metadata:
   name: frontend-app-deployment
spec:
   replicas: 1
   selector:
     matchLabels:
       app: frontend-app
   template:
      metadata: 
         name: frontend-app-pod
         labels:
            app: frontend-app
      spec:
        containers:
          - name: frontend-app-container
            image: amitfegade121/employee-app-client:latest
            ports:
               - containerPort: 80 
---

apiVersion: v1
kind: Service
metadata:
   name: frontend-app-svc
spec:
   type: NodePort
   selector:
      app: frontend-app  
   ports:
     - protocol: TCP
       port: 80
       targetPort: 80
       nodePort: 30001
         